AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MySecureS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: my-compliance-demo-bucket-test-1
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
# Testing CI pipeline again
